/**
 * Inventory Data
 * Last updated: 2025-10-12T20:29:56.481Z
 * Auto-generated by sync system
 */

const INVENTORY = [
    {
        "serialNumber": "P5-MS-507320-0612-101725",
        "cashPrice": 2865,
        "rto36": 132.64,
        "rto48": 119.38,
        "rto60": 110.19,
        "rto72": 98.79,
        "price": 2865,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-GSX-504265-1016-092025",
        "cashPrice": 5515,
        "rto36": 255.32,
        "rto48": 229.79,
        "rto60": 212.12,
        "rto72": 190.17,
        "price": 5515,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "U5-LB-504266-1016-092025",
        "cashPrice": 6386,
        "rto36": 295.65,
        "rto48": 266.08,
        "rto60": 245.62,
        "rto72": 220.21,
        "price": 6386,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-ES-504259-0812-092025",
        "cashPrice": 3510,
        "rto36": 162.5,
        "rto48": 146.25,
        "rto60": 135,
        "rto72": 121.03,
        "price": 3510,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "U5-GSX-502214-1016-083125",
        "cashPrice": 5630,
        "rto36": 260.65,
        "rto48": 234.58,
        "rto60": 216.54,
        "rto72": 194.14,
        "price": 5630,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-LB-493121-0812-061625",
        "cashPrice": 4625.6,
        "rto36": 214.15,
        "rto48": 192.73,
        "rto60": 177.91,
        "rto72": 159.5,
        "price": 4625.6,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-SLB-477885-1016-022325",
        "cashPrice": 6441,
        "rto36": 298.19,
        "rto48": 268.38,
        "rto60": 247.73,
        "rto72": 222.1,
        "price": 6441,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-SLB-473622-1232-121524",
        "cashPrice": 12205,
        "rto36": 565.05,
        "rto48": 508.54,
        "rto60": 469.42,
        "rto72": 420.86,
        "price": 12205,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-UX-471596-1232-112424",
        "cashPrice": 12931.4,
        "rto36": 598.68,
        "rto48": 538.81,
        "rto60": 497.36,
        "rto72": 445.91,
        "price": 12931.4,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-US-468743-1016-102624",
        "cashPrice": 6295,
        "rto36": 291.44,
        "rto48": 262.29,
        "rto60": 242.12,
        "rto72": 217.07,
        "price": 6295,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-C-468654-1232-102624",
        "cashPrice": 12125,
        "rto36": 561.34,
        "rto48": 505.21,
        "rto60": 466.35,
        "rto72": 418.1,
        "price": 12125,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-C-468653-0812-102624",
        "cashPrice": 5140,
        "rto36": 237.96,
        "rto48": 214.17,
        "rto60": 197.69,
        "rto72": 177.24,
        "price": 5140,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-ES-465888-0812-093024",
        "cashPrice": 3510,
        "rto36": 162.5,
        "rto48": 146.25,
        "rto60": 135,
        "rto72": 121.03,
        "price": 3510,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-CPLBC-461585-1440-081924",
        "cashPrice": 22971,
        "rto36": 1063.47,
        "rto48": 957.13,
        "rto60": 883.5,
        "rto72": 792.1,
        "price": 22971,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-UX-454665-0812-061024",
        "cashPrice": 4015.6,
        "rto36": 185.91,
        "rto48": 167.32,
        "rto60": 154.45,
        "rto72": 138.47,
        "price": 4015.6,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-UX-413420-1016-041523",
        "cashPrice": 5901,
        "rto36": 273.19,
        "rto48": 245.88,
        "rto60": 226.96,
        "rto72": 203.48,
        "price": 5901,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-SLB-410112-1016-030123",
        "cashPrice": 7016,
        "rto36": 324.81,
        "rto48": 292.33,
        "rto60": 269.85,
        "rto72": 241.93,
        "price": 7016,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-DS-249547-1012-071322",
        "cashPrice": 7857,
        "rto36": 363.75,
        "rto48": 327.38,
        "rto60": 302.19,
        "rto72": 270.93,
        "price": 7857,
        "location": "GPB Sales",
        "isRepo": false
    },
    {
        "serialNumber": "P5-C-466341-1228-100524R",
        "cashPrice": 11015,
        "rto36": 509.95,
        "rto48": 458.96,
        "rto60": 423.65,
        "rto72": 379.83,
        "price": 11015,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "5-MS-462975-0612-090224R",
        "cashPrice": 3035,
        "rto36": 140.51,
        "rto48": 126.46,
        "rto60": 116.73,
        "rto72": 104.66,
        "price": 3035,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "P5-C-451114-1232-041824R",
        "cashPrice": 13145,
        "rto36": 608.56,
        "rto48": 547.71,
        "rto60": 505.58,
        "rto72": 453.28,
        "price": 13145,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "5-UX-434957-1640-121423R",
        "cashPrice": 21190,
        "rto36": 981.02,
        "rto48": 882.92,
        "rto60": 815,
        "rto72": 730.69,
        "price": 21190,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "P5-GSX-407671-1012-011423R",
        "cashPrice": 5082,
        "rto36": 235.28,
        "rto48": 211.75,
        "rto60": 195.46,
        "rto72": 175.24,
        "price": 5082,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "5-GSX-249658-1232-072022R",
        "cashPrice": 11905,
        "rto36": 551.16,
        "rto48": 496.04,
        "rto60": 457.88,
        "rto72": 410.52,
        "price": 11905,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "5-GSX-255916-0812-011523R",
        "cashPrice": 4300,
        "rto36": 199.07,
        "rto48": 179.17,
        "rto60": 165.38,
        "rto72": 148.28,
        "price": 4300,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "P5-UX-250946-1012-081122R",
        "cashPrice": 4835,
        "rto36": 223.84,
        "rto48": 201.46,
        "rto60": 185.96,
        "rto72": 166.72,
        "price": 4835,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "5-C-137215-0816-062317R",
        "cashPrice": 6040,
        "rto36": 279.63,
        "rto48": 251.67,
        "rto60": 232.31,
        "rto72": 208.28,
        "price": 6040,
        "location": "GPB Sales",
        "isRepo": true
    },
    {
        "serialNumber": "P5-UX-498527-0812-072725",
        "cashPrice": 4015.6,
        "rto36": 185.91,
        "rto48": 167.32,
        "rto60": 154.45,
        "rto72": 138.47,
        "price": 4015.6,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-MS-496832-0612-071025",
        "cashPrice": 2890,
        "rto36": 133.8,
        "rto48": 120.42,
        "rto60": 111.15,
        "rto72": 99.66,
        "price": 2890,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-ES-495682-0812-070225",
        "cashPrice": 3510,
        "rto36": 162.5,
        "rto48": 146.25,
        "rto60": 135,
        "rto72": 121.03,
        "price": 3510,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-MS-488816-0612-051125",
        "cashPrice": 3035,
        "rto36": 140.51,
        "rto48": 126.46,
        "rto60": 116.73,
        "rto72": 104.66,
        "price": 3035,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "U5-UX-480672-1016-030125",
        "cashPrice": 5900,
        "rto36": 273.15,
        "rto48": 245.83,
        "rto60": 226.92,
        "rto72": 203.45,
        "price": 5900,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-US-464329-1016-091624",
        "cashPrice": 6295,
        "rto36": 291.44,
        "rto48": 262.29,
        "rto60": 242.12,
        "rto72": 217.07,
        "price": 6295,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-LB-464332-0816-091624",
        "cashPrice": 5455,
        "rto36": 252.55,
        "rto48": 227.29,
        "rto60": 209.81,
        "rto72": 188.1,
        "price": 5455,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-US-463599-1016-090824",
        "cashPrice": 6295,
        "rto36": 291.44,
        "rto48": 262.29,
        "rto60": 242.12,
        "rto72": 217.07,
        "price": 6295,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-SLB-461644-1016-082224",
        "cashPrice": 6325,
        "rto36": 292.82,
        "rto48": 263.54,
        "rto60": 243.27,
        "rto72": 218.1,
        "price": 6325,
        "location": "Columbia, La",
        "isRepo": false
    },
    {
        "serialNumber": "P5-MS-488817-0612-051125R",
        "cashPrice": 2775,
        "rto36": 128.47,
        "rto48": 115.63,
        "rto60": 106.73,
        "rto72": 95.69,
        "price": 2775,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "P5-UX-482716-1224-032025R",
        "cashPrice": 9186.8,
        "rto36": 425.31,
        "rto48": 382.78,
        "rto60": 353.34,
        "rto72": 316.79,
        "price": 9186.8,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "U5-UX-459897-1012-080124R",
        "cashPrice": 4655,
        "rto36": 215.51,
        "rto48": 193.96,
        "rto60": 179.04,
        "rto72": 160.52,
        "price": 4655,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "U5-SLB-455168-1020-062824R",
        "cashPrice": 7170,
        "rto36": 331.94,
        "rto48": 298.75,
        "rto60": 275.77,
        "rto72": 247.24,
        "price": 7170,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "P5-SLB-412665-1216-030323R",
        "cashPrice": 8052,
        "rto36": 372.78,
        "rto48": 335.5,
        "rto60": 309.69,
        "rto72": 277.66,
        "price": 8052,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "P5-GSX-251804-0812-082622R",
        "cashPrice": 4406,
        "rto36": 203.98,
        "rto48": 183.58,
        "rto60": 169.46,
        "rto72": 151.93,
        "price": 4406,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "5-UX-227769-0812-082021R",
        "cashPrice": 4400,
        "rto36": 203.7,
        "rto48": 183.33,
        "rto60": 169.23,
        "rto72": 151.72,
        "price": 4400,
        "location": "Columbia, La",
        "isRepo": true
    },
    {
        "serialNumber": "5-LB-141070-1232-081417R",
        "cashPrice": 13150,
        "rto36": 608.8,
        "rto48": 547.92,
        "rto60": 505.77,
        "rto72": 453.45,
        "price": 13150,
        "location": "Columbia, La",
        "isRepo": true
    }
];

const STATUS_OVERRIDES = {};

/**
 * Process raw inventory data through the decoder
 * Returns enhanced inventory with decoded information and status overrides
 */
function processInventory() {
    return INVENTORY.map(item => {
        const decoder = new SerialNumberDecoder(item.serialNumber);
        const details = decoder.getFullDetails();

        if (!details.valid) {
            console.error('Invalid serial number:', item.serialNumber);
            return null;
        }

        // Apply status overrides from automatic tracking
        const override = STATUS_OVERRIDES[item.serialNumber] || {};

        return {
            ...item,
            ...details,
            typeCode: details.type.code,
            typeName: details.type.name,
            sizeDisplay: details.size.display,
            width: details.size.width,
            length: details.size.length,
            dateBuilt: details.dateBuilt.display,
            isRepo: details.status === 'repo',
            autoStatus: override.status || 'available',
            statusMetadata: override.metadata || {}
        };
    }).filter(item => item !== null);
}

// Merge auto-tracked status with admin overrides
function mergeWithAdminSettings() {
    const processed = processInventory();
    const adminOverrides = localStorage.getItem('cpb_building_overrides');

    if (!adminOverrides) return processed;

    const overrides = JSON.parse(adminOverrides);

    return processed.map(building => {
        const adminOverride = overrides[building.serialNumber];
        if (adminOverride) {
            // Admin overrides take precedence
            return {
                ...building,
                adminStatus: adminOverride.status,
                hidden: adminOverride.hidden
            };
        }
        return building;
    });
}

// Make available globally
window.PROCESSED_INVENTORY = processInventory();
